//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashkiriaBase.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BashkiriaEntities : DbContext
    {
        public BashkiriaEntities()
            : base("name=BashkiriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<co_executors> co_executors { get; set; }
        public virtual DbSet<executors> executors { get; set; }
        public virtual DbSet<programs> programs { get; set; }
        public virtual DbSet<subprograms> subprograms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
