//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashkiriaBase.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BashkiriaEntities : DbContext
    {
        public BashkiriaEntities()
            : base("name=BashkiriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<co_executors> co_executors { get; set; }
        public virtual DbSet<executors> executors { get; set; }
        public virtual DbSet<programs> programs { get; set; }
        public virtual DbSet<subprograms> subprograms { get; set; }
    }
}
