//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashkiriaBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class subprograms
    {
        public int subprogram_id { get; set; }
        public Nullable<int> program_id { get; set; }
        public string subprogram_name { get; set; }
    
        public virtual programs programs { get; set; }
    }
}
